"""make resume id nullable

Revision ID: 0fffc7948723
Revises: 539c80649245
Create Date: 2026-07-21 18:14:10.281824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0fffc7948723'
down_revision: Union[str, Sequence[str], None] = '539c80649245'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interview_sessions', 'resume_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interview_sessions', 'resume_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
