"""added interview session

Revision ID: 34be1fcb88c3
Revises: 741d0f7c2f39
Create Date: 2026-08-01 20:09:33.479508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34be1fcb88c3'
down_revision: Union[str, Sequence[str], None] = '741d0f7c2f39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_sessions', sa.Column('resume_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'resume_summary')
    # ### end Alembic commands ###
