"""add interview_state to interview_sessions

Revision ID: 40d49314539b
Revises: f89f94f6151a
Create Date: 2026-07-17 02:19:06.150300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40d49314539b'
down_revision: Union[str, Sequence[str], None] = '0d866d4888ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_sessions', sa.Column('interview_state', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'interview_state')
    # ### end Alembic commands ###
