"""add resume summary to parsed resumes

Revision ID: 873f487a49e8
Revises: 34be1fcb88c3
Create Date: 2026-08-08 17:26:48.281550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '873f487a49e8'
down_revision: Union[str, Sequence[str], None] = '34be1fcb88c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parsed_resumes', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parsed_resumes', 'summary')
    # ### end Alembic commands ###
