"""add updated_at to resumes

Revision ID: 95a9e4d337a6
Revises: 873f487a49e8
Create Date: 2026-08-10 04:13:58.599955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95a9e4d337a6'
down_revision: Union[str, Sequence[str], None] = '873f487a49e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "resumes",
        sa.Column("updated_at", sa.DateTime(), nullable=True)
    )

    op.execute(
        "UPDATE resumes SET updated_at = uploaded_at WHERE updated_at IS NULL"
    )

    op.alter_column(
        "resumes",
        "updated_at",
        existing_type=sa.DateTime(),
        nullable=False,
    )



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'updated_at')
    # ### end Alembic commands ###
