"""make resume id non-nullable

Revision ID: f668f49f0a36
Revises: 0fffc7948723
Create Date: 2026-07-21 18:32:05.956339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f668f49f0a36'
down_revision: Union[str, Sequence[str], None] = '0fffc7948723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interview_sessions', 'resume_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interview_sessions', 'resume_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
