"""add email verification fields

Revision ID: ffd278039cff
Revises: f668f49f0a36
Create Date: 2026-07-29 03:21:16.257647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ffd278039cff'
down_revision: Union[str, Sequence[str], None] = 'f668f49f0a36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('auth_provider', sa.Enum('LOCAL', 'GOOGLE', name='authprovider'), nullable=False))
    op.add_column('users', sa.Column('otp_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('otp_purpose', sa.Enum('VERIFY_EMAIL', 'RESET_PASSWORD', name='otppurpose'), nullable=True))
    op.add_column('users', sa.Column('otp_expires_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_otp_sent_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('CANDIDATE', 'ADMIN', name='userrole'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('CANDIDATE', 'ADMIN', name='userrole'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('users', 'last_otp_sent_at')
    op.drop_column('users', 'otp_expires_at')
    op.drop_column('users', 'otp_purpose')
    op.drop_column('users', 'otp_hash')
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
